name: BigBrother
main: shoghicp\BigBrother\BigBrother
version: 1.0.0
api: 2.0.0
description: "Allows the connection of Minecraft: PC clients to PocketMine-MP servers"
author: shoghicp, UniversalMine
website: https://github.com/UniversalMine/PC-Client-Base/
